### ISSUE TITLE
abacus.js not generated

### ISSUE THREAD

**Issue by bncdemo** [dydxprotocol/v4-abacus#291]
Hello,

I am running the command: gradlew assembleJsPackage
The build is successful, but the abacus.js is not generated.

**Comment by bncdemo** [comment]
Still no abacus.js generated that the \v4-abacus-main\integration\Web\index.html could run

**Comment by prashanDYDX** [comment]
Without more info it's hard to provide any help here. I'd recommend checking out the Kotlin JS documentation and https://npm-publish.petuska.dev/latest/ (this is where `assembleJsPackage` comes from).

You can checkout https://github.com/dydxprotocol/v4-web/blob/main/scripts/install-local-abacus.js to see how abacus is integrated into the v4-web repo.

**Comment by prashanDYDX** [comment]
Yeah looks like those docs are a bit out of date, the next section is accurate though:
```
You can export the build to a package locally with the following commands:

cd ./build/packages/js

npm pack
```

In general, Kotlin JS is very poorly documented. :( I would get used to just digging around, running tasks, and seeing what is generated in the `build` folder.

**Comment by bncdemo** [comment]
> Yeah looks like those docs are a bit out of date, the next section is accurate though:
> 
> ```
> You can export the build to a package locally with the following commands:
> 
> cd ./build/packages/js
> 
> npm pack
> ```
> 
> In general, Kotlin JS is very poorly documented. :( I would get used to just digging around, running tasks, and seeing what is generated in the `build` folder.

npm pack run without error, but I got nowhere with that.

The abacus.js file is missing, running the \v4-abacus-main\integration\Web\index.html fail with abacus.js file not found. 

Do you know how to create the abacus.js, so the \v4-abacus-main\integration\Web\index.html able to run?

**Comment by prashanDYDX** [comment]
The sample is also out of date. If you look at the source for `index.html` you'll notice that it is pointing to the wrong location. 

abacusjs.js should be generated at `build/packages/js`.

**Comment by prashanDYDX** [comment]
Updated README.

**Comment by bncdemo** [comment]
> The sample is also out of date. If you look at the source for `index.html` you'll notice that it is pointing to the wrong location.
> 
> abacusjs.js should be generated at `build/packages/js`.
> 
> Looking at the `index.html` code, I'm honestly not even sure if it will run tbh.

I did go that route _before_ opening this issue ticket.

referencing the ../../build/packages/js/abacusjs.js file ends up with:
![aba](https://github.com/dydxprotocol/v4-abacus/assets/63590595/15d31a56-d149-4b98-9563-82576fa78619)

Can somebody update the index.html as well, so it is running without error?

**Comment by bncdemo** [comment]
Maybe the index.html creator jiajames knows the answer:
https://github.com/dydxprotocol/v4-abacus/commits?author=jiajames

**Comment by prashanDYDX** [comment]
Yeah, so this is diving into some of the details of how Kotlin JS organizes its JavaScript. Currently, the repo is configured to output UMD modules. You can include that module via NPM however you want (v4-web repo uses Vite to transform it into an ES module). 

The index.html example is trying to use Abacus as a normal JS file, which won't work (since it needs its dependencies). 

I'd really reference the v4-repo as a how-to on integrating Abacus into whatever frontend you are trying to build. Also highly recommend going through the Kotlin JS documentation to understand the process fully as it is quite complex.

We don't really have the bandwidth at the moment to get the index example working (and to your point we should probably delete it and just point to v4-web repo).
